<OBJECT CODEWORD-BULLHORN
    (DESC "Bullhorn")
    (SYNONYM BULLHORN)>

<OBJECT CODEWORD-CRABCLAW
    (DESC "Crabclaw")
    (SYNONYM CRABCLAW)>

<OBJECT CODEWORD-SPECULUM
    (DESC "Speculum")
    (SYNONYM SPECULUM)>

<OBJECT CODEWORD-WATERBEARER
    (DESC "Waterbearer")
    (SYNONYM WATERBEARER)>
