"Green Blood (ZIL)"

<CONSTANT GAME-TITLE "||Green Blood">
<CONSTANT GAME-DESCRIPTION "|Mark Smith and Dave Morris (1993)||Implemented in ZIL by SD Separa (2020)|">
<CONSTANT RELEASEID 6>
<CONSTANT IFID "E46D8D1A-2F4A-4665-BC81-0894C2E4DA9D">
<VERSION XZIP>

<INSERT-FILE "minilib">
<INSERT-FILE "story">

<ROUTINE GO ()
    <V-VERSION>
    <TELL CR "IFID: ">
    <TELL IFID>
    <CRLF>
    <GAME-BOOK>
    <QUIT-MSG>>
